// Shared vault data — used by discover.html and allocator.html.
// To add a vault: append one object to this array.
// Fields: name, curator, asset, apy (number), tvlRaw (number USD),
//         tvlDisplay (string), risk (string), riskTier ("low"|"medium"|"high"),
//         icon (HTML string), link (string)

const VAULTS = [
  {
    name: "Lido Staked ETH",
    curator: "Lido Finance",
    asset: "Ethereum",
    apy: 4.20,
    tvlRaw: 1_240_000_000,
    tvlDisplay: "$1.24B",
    risk: "A+",
    riskTier: "low",
    icon: '<img alt="ETH" class="w-6 h-6" src="https://lh3.googleusercontent.com/aida-public/AB6AXuA4iT1QGgk9YSPhDhuTxTnweEPErmG-iAXtRcvH3cyR4icBZWW-NkKYeVf-co5gHJcfB18X-R3p6vYyiVI69szuD3_ebLLWJdZfR75R-uX99YYZw3dscYsUrKM8cpsfkRsAcnUeklFVKY-TCC_U5V7cjbrDWLadhVWidD-ceCJ9eUInQG9V6YYn5PV2U9bPP73kNS93wwo43zhGF3wCgjj0W8k9f1gGqSdAsfztSrPmRMxM0zy3vzcpm-0IPDSCF-ZKtpMoO6OP4A0"/>',
    link: "vault_detail.html",
  },
  {
    name: "Circle Yield Plus",
    curator: "Circle",
    asset: "Stablecoins",
    apy: 5.15,
    tvlRaw: 850_000_000,
    tvlDisplay: "$850M",
    risk: "A",
    riskTier: "low",
    icon: '<img alt="USDC" class="w-6 h-6" src="https://lh3.googleusercontent.com/aida-public/AB6AXuDpeNg9PmhaOY7li73eV0QtjUnvNZSZzMExynF_kEC7pCv1pc7DSEQaSE6Ogsovopdiq_VF5219kRwSP0366xXDwkrA19FYlNI89Iz15_DrUVVarnvMqC3yjmB-CQxqGltKa7EW6ArSuUwa8p3DGWNxDTk6AXbi-Azc9nE5DI5pf0M8l_6fFGVlnuoZ92Y0PjDfFP9g-wBxZ09pB74zY9A2_VPaf-c9HBb9MnZo3MChJ065-i_A3TRY0U6cEfpNplQqhUOtKuRw_0c"/>',
    link: "vault_detail.html",
  },
  {
    name: "Aave V3 USDC",
    curator: "Aave",
    asset: "Stablecoins",
    apy: 6.80,
    tvlRaw: 2_100_000_000,
    tvlDisplay: "$2.1B",
    risk: "A",
    riskTier: "low",
    icon: '<span class="text-xs font-bold text-purple-600">AV</span>',
    link: "vault_detail.html",
  },
  {
    name: "BlackRock BUIDL",
    curator: "BlackRock",
    asset: "Stablecoins",
    apy: 5.05,
    tvlRaw: 510_000_000,
    tvlDisplay: "$510M",
    risk: "A+",
    riskTier: "low",
    icon: '<span class="text-xs font-bold text-slate-600">BR</span>',
    link: "vault_detail.html",
  },
  {
    name: "Ondo Finance USDY",
    curator: "Ondo Finance",
    asset: "Stablecoins",
    apy: 5.40,
    tvlRaw: 320_000_000,
    tvlDisplay: "$320M",
    risk: "A",
    riskTier: "low",
    icon: '<span class="text-xs font-bold text-cyan-600">ON</span>',
    link: "vault_detail.html",
  },
  {
    name: "Compound WBTC",
    curator: "Compound",
    asset: "Bitcoin",
    apy: 2.10,
    tvlRaw: 480_000_000,
    tvlDisplay: "$480M",
    risk: "A",
    riskTier: "low",
    icon: '<span class="text-xs font-bold text-orange-500">BTC</span>',
    link: "vault_detail.html",
  },
  {
    name: "Pendle PT-stETH",
    curator: "Pendle",
    asset: "Ethereum",
    apy: 8.40,
    tvlRaw: 320_000_000,
    tvlDisplay: "$320M",
    risk: "B+",
    riskTier: "medium",
    icon: '<span class="text-xs font-bold text-teal-600">PE</span>',
    link: "vault_detail.html",
  },
  {
    name: "Maple Finance USDC",
    curator: "Maple",
    asset: "Stablecoins",
    apy: 9.60,
    tvlRaw: 210_000_000,
    tvlDisplay: "$210M",
    risk: "B",
    riskTier: "medium",
    icon: '<span class="text-xs font-bold text-green-600">MF</span>',
    link: "vault_detail.html",
  },
  {
    name: "Gauntlet USDC Frontier",
    curator: "Gauntlet",
    asset: "Stablecoins",
    apy: 4.32,
    tvlRaw: 3_600_000,
    tvlDisplay: "$3.6M",
    risk: "B+",
    riskTier: "medium",
    icon: '<span class="text-xs font-bold text-blue-600">GU</span>',
    link: "vault_detail.html",
  },
  {
    name: "Clearpool USDC",
    curator: "Clearpool",
    asset: "Stablecoins",
    apy: 11.30,
    tvlRaw: 95_000_000,
    tvlDisplay: "$95M",
    risk: "B",
    riskTier: "medium",
    icon: '<span class="text-xs font-bold text-indigo-600">CP</span>',
    link: "vault_detail.html",
  },
  {
    name: "Goldfinch Senior Pool",
    curator: "Goldfinch",
    asset: "Stablecoins",
    apy: 12.50,
    tvlRaw: 85_000_000,
    tvlDisplay: "$85M",
    risk: "C+",
    riskTier: "high",
    icon: '<span class="text-xs font-bold text-yellow-600">GF</span>',
    link: "vault_detail.html",
  },
  {
    name: "Ribbon Finance ETH",
    curator: "Ribbon",
    asset: "Ethereum",
    apy: 15.20,
    tvlRaw: 45_000_000,
    tvlDisplay: "$45M",
    risk: "C+",
    riskTier: "high",
    icon: '<span class="text-xs font-bold text-red-600">RF</span>',
    link: "vault_detail.html",
  },
];
